#!/bin/env bash

# Declare static variables:
user=$USER
host=$HOSTNAME
backupdrive=/media/"$user"/BU_Drive
backupdirectory="$backupdrive"/BU_Backups/"$host"
RSYNC_CMD='sudo rsync -aH --delete --info=progress2'
DEFAULT_BACKUP_DIRS='/etc /home'

# Check for less and rsync, install if needed:
dpkg -l | grep -qw rsync || sudo apt install rsync -yyq
dpkg -l | grep -qw less || sudo apt install less -yyq

# functions
drive_test() {

# Checking for any USB drive:
if [[ ! $(lsblk -S -o  TRAN | grep 'usb') = *usb* ]]; then
    echo $'\n'$"BU Error: No USB drive connected!" >&2
    echo "- Check to see that BU_Drive is plugged in." >&2
    echo "- Pleese run 'bu --help' to learn about drive setup. :)" >&2
    exit 1
fi

# Checking for a USB drive that is setup for BU:
if [ ! -d /media/"$user"/BU_Drive ]; then
    echo $'\n'$"BU Error: No USB drive with a partition labeled "BU_Drive!"" >&2
    echo "- The drive(s) you have plugged in are not ready for use with BU." >&2
    echo "- Don't launch BU as root or with 'sudo bu.'" >&2
    echo "- Please run 'bu --help' to learn about drive setup. :)" >&2
    exit 1
fi

}

add_exclude() {
    if [ -f /bu.exclude ]; then
        exit RSYNC_CMD += "--exclude-from=bu.exclude"
}

add_include(){
    if [ -f /bu.include ]; then
        exit RSYNC_CMD += "--files-from=bu.include"
}

apt_backup(){

}

iptables_backup(){

}

cron_backup(){

}

backup() {

	# Check for sudo privilages:
	echo "Checking for sudo privileges..."
	sudo ls >/dev/null

	# Making sure user has ownership of the BU_Drive:
	echo "Changing ownership of BU_Drive to $user..."
	sudo chown "$user" /media/"$user"/BU_Drive/

	# Creating machine specific directories:
	echo "Checking for/creating machine specific directories..."
	mkdir -p /media/"$user"/BU_Drive/BU_Backups/"$host"

	# Check if directory for host machine was successfully created:

	if mkdir -p /media/"$user"/BU_Drive/BU_Backups/"$host"; then
		echo "...Done. BU_Drive is ready."
	else
		echo $'\n'$"BU Error: Could not create directroy for $host!" >&2
		echo "- Backup aborted. Check the status of the BU_Drive." >&2
		exit 1
	fi

	echo "Backing up /etc and /home to BU_Drive/BU_Backups/$host/..."

	# Check for status of backup and exit:
	if sudo rsync -aH --delete --info=progress2 --exclude-from=bu.exclude /etc /home /media/"$user"/BU_Drive/BU_Backups/"$host"/; then
		# Clear any accidental input during backup:
		read -r -t 1 -n 10000
		echo "Wait! Syncing Drives..."
		sync
		echo "...done"
		exit
	else
		# Clear any accidental input during backup:
		read -r -t 1 -n 10000
		echo "There were errors! Try running the caoomnd again to correct them." >&2
		echo "- If errors persist then you may have corrupt files or failing hardware." >&2	
		exit 1
	fi
}

drive_test
add_include
add_exclude
default_backup
apt_backup
iptables_backup
cron_backup
